# brew
brew "git"
brew "tree"
brew "nvm"

# cask(GUI)
cask "docker"
cask "raycast"
cask "ghostty"
cask "rectangle"
cask "cursor"
cask "dbeaver-community"
cask "slack"
cask "obsidian"
cask "intellij-idea"
cask "figma"
cask "datagrip"